# Site settings
title: CI and CD with GitHub
description: Surely something useful could be here?
email: patrickmckenna@github.com
github_username:  patrickmckenna
baseurl:
url: https://cicd-demo.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
