# Site settings
title: CI and CD with GitHub
description: A demo blog
email: fermentedbeats@github.com
github_username:  fermentedbeats
baseurl:
url: https://githubtraining-cicd-demo.herokuapp.comBROKEN
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
