#!/bin/bash

# Usage: add-status <sha>

set -e

curl -H "Authorization: token $GITHUBSTUDENT_TOKEN" \
  https://api.github.com/repos/githubstudent/cicd-demo/statuses/"$1" \
  -d '{"state": "pending", "target_url": "https://google.com", "description": "example", "context": "demo statuses API"}'
